### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by andress134** [JimmyLaurent/hcaptcha-solver#1]
Hello, i testing to bypass hcaptcha, but something wrong

Here is my exemple code

```js
const cloudflareScraper = require('cloudflare-scraper');
const url = process.argv[2]
  return new Promise((resolve, reject) => {
    solveCaptcha(url, {
    }) 
      .then(response => {
        resolve(response);
        console.log(response);
      })
      .catch((error) => {
        console.log(error);
        return reject(error);
      });
  });
}
```

Get error 

`UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)`

**Comment by JimmyLaurent** [comment]
Hi, 

I think your error is coming from "solveCaptcha": it is never declared. 
So it throw inside your promise instead of rejecting wich is why you have this unhandled promise rejection.
