### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by LucasLauDev** [JimmyLaurent/hcaptcha-solver#15]
`let text = req.params.text;
  const headers = {
      "user-agent":
        "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
    };
    let url = `https://www.curseforge.com/minecraft/bukkit-plugins/search?category=&search=${text}`
    try {
      const response = await solveCaptcha(url);
      console.log(response);
      // F0_eyJ0eXAiOiJKV1Q...
    } catch (error) {
      console.log(error);
    }
  let Search = await fetch(url, { headers })
  const html = await Search.text();
  res.send(html)`
It will still in hcaptcha page

**Comment by FluffyDev1** [comment]
it works but u dont understand what to do

**Comment by QC-Development** [comment]
I found that it is my IP problem cuz it is shared hosting

**Comment by LucasLauDev** [comment]
I found that it is my IP problem cuz it is shared hosting
