### ISSUE TITLE
hCaptcha changed the main script

### ISSUE THREAD

**Issue by Numenorean** [JimmyLaurent/hcaptcha-solver#3]
I tried bypass it for site named faceit, but now i see that it has another script, which hardly obfuscated and has dom elements, so i got error UnhandledPromiseRejectionWarning: ReferenceError: Window is not defined
Here is new script: https://assets.hcaptcha.com/c/500c658/hsw.js

**Comment by JimmyLaurent** [comment]
It's the script for browsers supporting web assembly. 
For older browsers this one is used : https://assets.hcaptcha.com/c/7f492a3/hsl.js

Anyway the bruteforce bypass method used in this package doesn't seem to work anymore.

**Comment by Numenorean** [comment]
Yeah, with hsl script i always get response with captcha pictures. So is it possible to remake hsw script to nodejs support?

**Comment by JimmyLaurent** [comment]
Yes but why would you want yo do this ?

**Comment by Numenorean** [comment]
Becouse it's too expensive to pay for captcha solution services like anticaptcha or rucaptcha. With nodejs it would be much easier

**Comment by JimmyLaurent** [comment]
I think you misread this:
`Anyway the bruteforce bypass method used in this package doesn't seem to work anymore.`

To clarify, this bypass is dead. 
The problem is not this hsw script, the problem is recognizing images since the bruteforce method doesn't work anymore.

**Comment by Numenorean** [comment]
but on the faceit.com i didn't see any captcha images, it was fully automaticaly

**Comment by JimmyLaurent** [comment]
An invisible captcha, It's unlikely.
I didn't see it on you site, wich page is it on ?

**Comment by Numenorean** [comment]
> An invisible captcha, It's unlikely.
> I didn't see it on you site, wich page is it on ?

its here https://www.faceit.com/en/login

**Comment by JimmyLaurent** [comment]
It seems to be a recaptcha.

**Comment by Numenorean** [comment]
> It seems to be a recaptcha.

yes it looks like recaptcha, but it isn't, you can see requests and make sure of it

**Comment by JimmyLaurent** [comment]
Yes indeed. They have invisible captchas.

You have a limited support in the last version, it doesn't work every time so you may have to do some tweaks.

**Comment by Numenorean** [comment]
> Yes indeed. They have invisible captchas.
> 
> You have a limited support in the last version, it doesn't work every time so you may have to do some tweaks.

thank you so much. now it works :heart:
